name: CI-MicrosoftTeamsApi-master-official

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution (with warnings)
      run: dotnet build --no-restore
    - name: Pack the library
      run: dotnet pack '*.csproj' --output nuget-packages --configuration Release
    - name: Publish the library to nuget.org
      run: dotnet nuget push '*.nupkg' --api-key oy2pbxpivyo4wqe3dkqagjkgpxmdiabedeqqmv3yuwcx6a --source https://api.nuget.org/v3/index.json
