name: CI-MicrosoftTeamsApi-master-official

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution (with warnings)
      run: dotnet build --no-restore
    - name: Pack the library
      run: dotnet pack --output nuget-packages --configuration Release
    - name : Publish the compiled code to artifacts
      run: dotnet publish -p:PublishProfile=FolderProfile --configuration Release
    - name : Upload published artifacts to staging area
      uses : actions/upload-artifact@v2
      with:
        name: Microsoft.Teams.Api.SourceCode
        path: /home/runner/work/Microsoft.Teams.Api/Microsoft.Teams.Api/bin/Release/netstandard2.1/publish/
    - name: Publish the library to nuget.org
      run: dotnet nuget push /home/runner/work/Microsoft.Teams.Api/Microsoft.Teams.Api/bin/Release/*.nupkg --api-key oy2pbxpivyo4wqe3dkqagjkgpxmdiabedeqqmv3yuwcx6a --source https://api.nuget.org/v3/index.json
